import Head from 'next/head'
import Image from 'next/image'
import HeadNav from '../components/nav';
import FullSlide from '../components/fullSlide';
import SwiperSlider from '../components/swiperSlider';

export default function Home() {
  return (
    <div>
      <Head>
        <title>WIDTOWN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadNav />

			<FullSlide 
			  img="/static/wide1.png"
				title="기하학 가면을 쓴 현대인의 자화상 아티스트 이보영" 
				subtitle="2023.03.04 오픈"
			>
			</FullSlide>

			<SwiperSlider imageShape="square" title="한국 알앤비? 여기요" subtitle="지금 주목해야할 멋진 아티스트들을 확인하세요."></SwiperSlider>
			<SwiperSlider imageShape="square" title="New Release #85" subtitle="지금 주목해야할 멋진 아티스트들을 확인하세요."></SwiperSlider>
			<SwiperSlider imageShape="square" title="한국 힙합 이즈 고" subtitle="지금 주목해야할 멋진 아티스트들을 확인하세요."></SwiperSlider>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
